version: '2.1'
services:
  db:
    image: postgres
    network_mode: "bridge"
  web:
    image: "377941069960.dkr.ecr.us-east-1.amazonaws.com/react-flux-gulp-starter/web:${ENV:-local}"
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "bridge"
    command: 'python manage.py runserver'
    working_dir: /app/user
    environment:
      PORT: 8000
