#!/bin/bash
chmod +x $HOME/.profile
. $HOME/.profile

CACHE_PREFIX="c-"
BASE_PATH="/srv/active"
STATIC_DIR="$BASE_PATH/collected-static"
CACHE_DIR="$BASE_PATH/caches"
MAX_KEEP=5

VERSION_FILE="$BASE_PATH/VERSION"

restart_if_exists()
{
    ex=$(svcs | grep $1)
    if [ -n "$ex" ]; then
        svcadm restart $1
    fi
}

purge_cache_directories()
{
    # Delete the oldest directories until there are only max left.
    max=$1
    while [ "$(ls $CACHE_DIR | wc -l)" -gt $max ]; do
        list=$(find "$CACHE_DIR" -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p:\n' \
            2>/dev/null | sort -n)
        line=$(echo $list | cut -s -d ":" -f 1)
        dir="${line#* }"
        rm -rf $dir
    done

    # Delete broken links
    find -L $STATIC_DIR -maxdepth 1 -type l -exec rm "{}" \;
}

copy_lastest_to_cache_dir()
{
    hash_dir=$1
    mkdir -p "$CACHE_DIR/$hash_dir"
    rsync -rpog --delete "$STATIC_DIR/" "$CACHE_DIR/$hash_dir"
    ln -sf "$CACHE_DIR/$hash_dir/" "$STATIC_DIR/$hash_dir"
}

refname=unset
while read oldrev newrev ref
do
    refname=$ref
done
branch=${refname#*/*/}
echo "Checking out $branch"
GIT_WORK_TREE=$BASE_PATH git checkout -f $branch

staticrev=$(git log --pretty=format:"%h" -n 1 $branch -- project/static)
echo $staticrev > $VERSION_FILE

copy_lastest_to_cache_dir "$CACHE_PREFIX$staticrev"

restart_if_exists gunicorn
restart_if_exists nginx

# Purge old static
purge_cache_directories $MAX_KEEP
